"use client";

import { Check, Database, Download, EyeOff, Info, Laptop, Moon, Palette, RotateCcw, Save, ShieldCheck, SlidersHorizontal, Sun, UserCheck } from "lucide-react";
import { Card } from "@/components/ui/common";
import { useApp } from "@/lib/context/app-context";
import type { UserSettings } from "@/lib/types";

export function SettingsPanel() {
  const { settings, updateSettings, profiles, toast } = useApp();
  const set = <K extends keyof UserSettings>(key: K, value: UserSettings[K]) => { updateSettings({ [key]: value }); toast("Settings updated", "Your preference was saved in this browser."); };
  return <div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections"><a href="#appearance"><Palette size={16}/>Appearance</a><a href="#processing"><SlidersHorizontal size={16}/>Processing Defaults</a><a href="#review-rules"><UserCheck size={16}/>Review Rules</a><a href="#demo"><ShieldCheck size={16}/>Demo Mode</a><a href="#export"><Download size={16}/>Export Preferences</a></nav><div className="settings-sections">
    <Card className="settings-card" id="appearance"><div className="settings-heading"><span><Palette size={19}/></span><div><h2>Appearance</h2><p>Choose how Textract Studio looks on this device.</p></div></div><div className="appearance-options">{[["system","System",Laptop],["dark","Dark",Moon],["light","Light",Sun]].map(([value,label,Icon]) => <button key={String(value)} className={settings.appearance === value ? "active" : ""} onClick={() => set("appearance", value as UserSettings["appearance"])}><span>{typeof Icon !== "string" && <Icon size={20}/>}</span><strong>{String(label)}</strong><small>{value === "system" ? "Match your device" : `${String(label)} interface`}</small>{settings.appearance === value && <Check size={15}/>}</button>)}</div></Card>
    <Card className="settings-card" id="processing"><div className="settings-heading"><span><SlidersHorizontal size={19}/></span><div><h2>Processing defaults</h2><p>Defaults applied to new frontend demo jobs.</p></div></div><div className="settings-control"><label><span><strong>Default confidence threshold</strong><small>Results below this value require review.</small></span><em>{settings.confidenceThreshold}%</em></label><input type="range" min="50" max="99" value={settings.confidenceThreshold} onChange={(event) => updateSettings({confidenceThreshold:Number(event.target.value)})} onMouseUp={() => toast("Threshold updated", `Review threshold set to ${settings.confidenceThreshold}%.`)} /></div><div className="settings-row"><span><strong>Default extraction profile</strong><small>Used when Automatic processing is selected.</small></span><select defaultValue="General Document"><option>General Document</option><option>Invoice / Receipt</option><option>Application Form</option><option>Contract</option></select></div><div className="settings-foot"><Database size={15}/>{profiles.length} extraction profiles are available locally.</div></Card>
    <Card className="settings-card" id="review-rules"><div className="settings-heading"><span><UserCheck size={19}/></span><div><h2>Review rules</h2><p>Control which results enter Confidence-Guided Review.</p></div></div><SwitchRow label="Auto-send low confidence to review" description="Route fields below the threshold into the local review queue." checked={settings.autoReview} onChange={(checked) => set("autoReview",checked)}/><SwitchRow label="Privacy presentation mode" description="Mask sensitive-looking values in the UI. This is not PII detection." checked={settings.privacyMode} onChange={(checked) => set("privacyMode",checked)}/><div className="settings-info"><Info size={16}/><p>Future PII classification would require an additional backend service. Textract Studio does not claim Textract identifies PII automatically.</p></div></Card>
    <Card className="settings-card" id="demo"><div className="settings-heading"><span><ShieldCheck size={19}/></span><div><h2>Demo Mode</h2><p>Safe frontend simulation for development and presentation.</p></div><span className="demo-enabled"><i/>ENABLED</span></div><div className="demo-status-grid"><div><strong>AWS connections</strong><span>Not configured</span></div><div><strong>File transfer</strong><span>Browser only</span></div><div><strong>Mock data</strong><span>Loaded</span></div><div><strong>Local persistence</strong><span>Enabled</span></div></div><div className="demo-mode-explain"><EyeOff size={18}/><div><strong>No credentials or AWS resources are required.</strong><p>Service boundaries are represented through a demo adapter ready to be replaced by a backend implementation.</p></div></div></Card>
    <Card className="settings-card" id="export"><div className="settings-heading"><span><Download size={19}/></span><div><h2>Export preferences</h2><p>Choose the default local result format.</p></div></div><div className="export-options">{(["json","csv","txt"] as const).map((value) => <button className={settings.exportFormat === value ? "active" : ""} onClick={() => set("exportFormat",value)} key={value}><span>.{value}</span><strong>{value.toUpperCase()}</strong><small>{value === "json" ? "Structured fields and geometry" : value === "csv" ? "Tabular fields and line items" : "Plain extracted text"}</small>{settings.exportFormat === value && <Check size={15}/>}</button>)}</div></Card>
    <div className="settings-save-bar"><span><Save size={16}/>Changes save automatically to localStorage.</span><button className="btn btn-secondary" onClick={() => { updateSettings({appearance:"dark",confidenceThreshold:85,autoReview:true,privacyMode:false,exportFormat:"json"}); toast("Settings reset","Default demo preferences restored."); }}><RotateCcw size={15}/>Reset defaults</button></div>
  </div></div>;
}
function SwitchRow({label,description,checked,onChange}:{label:string;description:string;checked:boolean;onChange:(checked:boolean)=>void}) { return <label className="switch-row settings-switch"><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" checked={checked} onChange={(event)=>onChange(event.target.checked)}/><i/></label>; }

