"use client";

import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowLeft, Braces, Check, CheckCircle2, ClipboardCheck, Download, Expand, Eye, EyeOff, FileJson, FileText, Focus, Grid3X3, LayoutDashboard, Minus, MoreHorizontal, Plus, RotateCw, ScanLine, Search, Signature, Table2, Text } from "lucide-react";
import { Card, Confidence, CopyButton, DownloadButton, EmptyState, StatusBadge } from "@/components/ui/common";
import { PipelineIndicator } from "@/components/ui/pipeline-indicator";
import { useApp } from "@/lib/context/app-context";
import { demoDocuments, invoiceResult } from "@/lib/mock/data";
import type { BoundingBox } from "@/lib/types";
import { cn, downloadFile, maskValue } from "@/lib/utils/format";

const tabs = ["Overview", "Text", "Fields", "Tables", "Queries", "Signatures", "Layout", "Raw JSON"] as const;
type Tab = typeof tabs[number];

export function DocumentWorkspace({ id }: { id: string }) {
  const document = demoDocuments.find((item) => item.id === id); const result = useMemo(() => ({ ...invoiceResult, documentId: id, pages: document?.pages ?? 2, documentType: document?.type ?? "Invoice", overallConfidence: document?.confidence ?? 94.8 }), [id, document]);
  const { settings, updateSettings, toast } = useApp(); const [tab, setTab] = useState<Tab>("Overview"); const [selected, setSelected] = useState<BoundingBox | null>(null); const [selectedLabel, setSelectedLabel] = useState(""); const [heatmap, setHeatmap] = useState(false); const [zoom, setZoom] = useState(88); const [rotation, setRotation] = useState(0); const [page, setPage] = useState(1); const viewerRef = useRef<HTMLDivElement>(null);
  if (!document) return <EmptyState icon={<FileText size={30} />} title="Document not found" description={`No demo document matches “${id}”. It may have been removed from local demo data.`} action={<Link className="btn btn-primary" href="/documents">Back to Documents</Link>} />;
  const trace = (box: BoundingBox, label: string) => { setSelected(box); setSelectedLabel(label); setPage(box.page); toast("Source Trace activated", `${label} highlighted on page ${box.page}.`); };
  const exportAll = (format: "json" | "csv" | "txt") => {
    const content = format === "json" ? JSON.stringify(result, null, 2) : format === "csv" ? `Field,Value,Confidence\n${result.fields.map((field) => `"${field.label}","${field.value}",${field.confidence}`).join("\n")}` : result.fullText;
    downloadFile(`${document.id}-extraction.${format}`, content, format === "json" ? "application/json" : format === "csv" ? "text/csv" : "text/plain"); toast("Export created", `${format.toUpperCase()} downloaded locally.`);
  };
  return <div className="document-workspace reveal">
    <header className="workspace-header"><div><Link href="/documents" className="back-link"><ArrowLeft size={16} /> Documents</Link><div className="workspace-title"><span><FileText size={20} /></span><div><h1>{document.name}</h1><p>{document.id} · {document.pages} pages · Processed {document.uploadedAt.toLowerCase()}</p></div><StatusBadge status={document.status} /></div></div><div className="workspace-actions"><button className={cn("btn btn-secondary", settings.privacyMode && "active")} onClick={() => updateSettings({ privacyMode: !settings.privacyMode })}>{settings.privacyMode ? <EyeOff size={16} /> : <Eye size={16} />} Privacy {settings.privacyMode ? "On" : "Off"}</button><div className="export-menu"><button className="btn btn-primary" onClick={() => exportAll(settings.exportFormat)}><Download size={16} /> Export {settings.exportFormat.toUpperCase()}</button><button className="btn btn-primary export-more" onClick={() => exportAll("csv")} aria-label="Quick export CSV"><MoreHorizontal size={16} /></button></div></div></header>
    <PipelineIndicator activeIndex={5} complete compact />
    <div className="workspace-body">
      <section className="viewer-panel" ref={viewerRef}><div className="viewer-toolbar"><div className="tool-group"><button className="icon-btn" onClick={() => setZoom(Math.max(50, zoom - 10))} aria-label="Zoom out"><Minus size={17} /></button><span>{zoom}%</span><button className="icon-btn" onClick={() => setZoom(Math.min(150, zoom + 10))} aria-label="Zoom in"><Plus size={17} /></button><button className="toolbar-btn" onClick={() => setZoom(88)}><Focus size={16} /> Fit</button></div><div className="tool-group"><button className="toolbar-btn" onClick={() => setPage(Math.max(1, page - 1))} disabled={page === 1}>‹</button><span>Page <strong>{page}</strong> of {document.pages}</span><button className="toolbar-btn" onClick={() => setPage(Math.min(document.pages, page + 1))} disabled={page === document.pages}>›</button></div><div className="tool-group"><button className="icon-btn" onClick={() => setRotation((rotation + 90) % 360)} aria-label="Rotate page"><RotateCw size={17} /></button><button className="icon-btn" onClick={() => void viewerRef.current?.requestFullscreen?.()} aria-label="Fullscreen viewer"><Expand size={17} /></button></div></div>
        <div className="viewer-canvas"><div className="viewer-hud-label" aria-hidden="true"><span>SOURCE_DOCUMENT</span><em>PAGE_{String(page).padStart(2,"0")}</em></div><div className="viewer-hud-corners" aria-hidden="true"><i /><i /><i /><i /></div><div className="paper-wrap" style={{ width: `${zoom}%` }}><MockInvoicePage page={page} rotation={rotation} /><div className="page-overlays">{selected?.page === page && <span className="source-highlight" style={{ left: `${selected.left}%`, top: `${selected.top}%`, width: `${selected.width}%`, height: `${selected.height}%` }}><em>{selectedLabel}</em></span>}{heatmap && result.fields.filter((field) => field.boundingBox.page === page).map((field, index) => <span title={`${field.label}: ${field.confidence}%`} className={cn("heat-region", field.confidence >= 90 ? "high" : field.confidence >= 80 ? "medium" : "low")} key={field.id} style={{ left: `${field.boundingBox.left}%`, top: `${field.boundingBox.top}%`, width: `${field.boundingBox.width}%`, height: `${field.boundingBox.height}%`, animationDelay: `${Math.min(index, 8) * 35}ms` }} />)}</div></div></div>
        <div className="viewer-footer"><button className={cn("heatmap-toggle", heatmap && "active")} onClick={() => setHeatmap(!heatmap)}><span><Grid3X3 size={15} /> Confidence Heatmap</span><i /></button>{heatmap && <div className="heat-legend"><span><i className="high" /> High 90–100</span><span><i className="medium" /> Medium 80–89.99</span><span><i className="low" /> Low below 80</span></div>}<div className="source-trace-info"><ScanLine size={15} /><span><strong>Source Trace</strong><small>Trace extracted data back to its exact source location.</small></span></div></div>
      </section>
      <section className="results-panel"><div className="result-tabs" role="tablist">{tabs.map((item) => <button role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</div><div className="result-content" key={tab}>
        {tab === "Overview" && <OverviewTab />}{tab === "Text" && <TextTab />}{tab === "Fields" && <FieldsTab privacy={settings.privacyMode} onTrace={trace} />}{tab === "Tables" && <TablesTab />}{tab === "Queries" && <QueriesTab onTrace={trace} />}{tab === "Signatures" && <SignaturesTab onTrace={trace} />}{tab === "Layout" && <LayoutTab />}{tab === "Raw JSON" && <RawJsonTab />}
      </div></section>
    </div>
  </div>;
}

function MockInvoicePage({ page, rotation }: { page: number; rotation: number }) {
  if (page > 1) return <div className="invoice-page page-two" style={{ transform: `rotate(${rotation}deg)` }}><div className="invoice-brand"><span>ACME</span><small>SYSTEMS</small></div><h2>Payment terms & authorization</h2><p>Payment is due within 15 days from the date of invoice. Please reference the invoice number in all correspondence.</p><div className="terms-lines">{Array.from({ length: 8 }, (_, index) => <i key={index} />)}</div><div className="signature-area"><span>Authorized signature</span><b>Arun Mehta</b><i /></div><footer>ACME Systems · Bengaluru, Karnataka · accounts@acmesystems.example</footer></div>;
  return <div className="invoice-page" style={{ transform: `rotate(${rotation}deg)` }}><div className="invoice-top"><div className="invoice-brand"><span>ACME</span><small>SYSTEMS</small></div><h2>INVOICE</h2></div><div className="invoice-details"><div><small>FROM</small><strong>Acme Systems</strong><p>14 Cloud Avenue<br/>Bengaluru, Karnataka 560001<br/>accounts@acmesystems.example</p></div><div><dl><dt>Invoice Number</dt><dd>INV-2026-1042</dd><dt>Invoice Date</dt><dd>02 Sep 2026</dd><dt>PO Number</dt><dd>PO-7482O</dd></dl></div></div><div className="bill-to"><small>BILL TO</small><strong>Meridian Retail Pvt. Ltd.</strong><p>98 Residency Road, Bengaluru</p></div><table><thead><tr><th>DESCRIPTION</th><th>QTY</th><th>RATE</th><th>AMOUNT</th></tr></thead><tbody><tr><td>Cloud Infrastructure Setup</td><td>1</td><td>₹32,000.00</td><td>₹32,000.00</td></tr><tr><td>Technical Support</td><td>4</td><td>₹2,000.00</td><td>₹8,000.00</td></tr></tbody></table><div className="invoice-totals"><dl><dt>Subtotal</dt><dd>₹40,000.00</dd><dt>GST (6.45%)</dt><dd>₹2,580.00</dd><dt className="total">TOTAL AMOUNT</dt><dd className="total">₹42,580.00</dd></dl></div><div className="tax-line"><small>TAX ID</small><strong>29ABCDE1234F1Z5</strong></div><p className="thank-you">Thank you for your business.</p><footer>Payment due within 15 days · Page 1 of 2</footer></div>;
}

function TabHeader({ icon, title, count, children }: { icon: React.ReactNode; title: string; count?: string; children?: React.ReactNode }) { return <div className="tab-heading"><div><span>{icon}</span><div><h2>{title}</h2>{count && <p>{count}</p>}</div></div>{children}</div>; }
function OverviewTab() { const r = invoiceResult; return <div className="tab-stack"><TabHeader icon={<LayoutDashboard size={18} />} title="Extraction overview" count="Normalized demo result" /><div className="overview-hero"><div><span>Overall confidence</span><strong>{r.overallConfidence}%</strong><Confidence value={r.overallConfidence} label={false} /></div><span className="quality-badge"><CheckCircle2 size={16} /> High quality</span></div><div className="overview-metrics">{[["Document type",r.documentType],["Pages",r.pages],["Processing time",r.processingTime],["Fields detected",r.fields.length],["Tables detected",r.tables.length],["Signatures",r.signatures.length]].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><Card className="confidence-distribution"><div className="card-heading"><div><h3>Confidence distribution</h3><p>Across extracted blocks</p></div></div><div className="distribution-bars">{[["High confidence",84,"126 blocks","high"],["Medium confidence",12,"18 blocks","medium"],["Needs review",4,"6 blocks","low"]].map(([label,value,count,level]) => <div key={label}><span>{label}</span><div><i className={String(level)} style={{ width: `${value}%` }} /></div><strong>{value}%</strong><small>{count}</small></div>)}</div></Card><div className="review-callout"><span><ClipboardCheck size={19} /></span><div><strong>2 fields need human review</strong><p>Low-confidence values are already in the Confidence-Guided Review queue.</p></div><Link href="/review">Review fields</Link></div></div>; }
function TextTab() { const [search, setSearch] = useState(""); const text = invoiceResult.fullText; return <div className="tab-stack"><TabHeader icon={<Text size={18} />} title="Detected text" count={`${text.length} characters`}><CopyButton value={text} /></TabHeader><label className="inline-search"><Search size={15} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search extracted text" /></label><pre className="extracted-text">{search ? text.split(new RegExp(`(${search.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")})`, "ig")).map((part, index) => part.toLowerCase() === search.toLowerCase() ? <mark key={index}>{part}</mark> : part) : text}</pre><div className="info-callout"><ScanLine size={16} /> Text is normalized demo content. A backend can later preserve block-level confidence and geometry.</div></div>; }
function FieldsTab({ privacy, onTrace }: { privacy: boolean; onTrace: (box: BoundingBox, label: string) => void }) { return <div className="tab-stack"><TabHeader icon={<Braces size={18} />} title="Extracted fields" count={`${invoiceResult.fields.length} key-value pairs`} /><div className="field-list">{invoiceResult.fields.map((field) => <button className="field-row" key={field.id} onClick={() => onTrace(field.boundingBox, field.label)}><span className="field-status-icon">{field.confidence < 80 ? <AlertTriangle /> : <Check />}</span><span className="field-main"><small>{field.label}</small><strong>{privacy && field.sensitive ? maskValue(field.value) : field.value}</strong></span><Confidence value={field.confidence} /><StatusBadge status={field.reviewStatus ?? "Pending"} /><span className="trace-action"><Focus size={15} /> Trace</span></button>)}</div><div className="threshold-note"><AlertTriangle size={15} /> Current review threshold: <strong>85%</strong>. Values below it are routed to review.</div></div>; }
function TablesTab() { const [raw, setRaw] = useState(false); const table = invoiceResult.tables[0]; const csv = `${table.headers.join(",")}\n${table.rows.map((row) => row.map((cell) => `"${cell}"`).join(",")).join("\n")}`; return <div className="tab-stack"><TabHeader icon={<Table2 size={18} />} title="Extracted tables" count={`${table.rows.length} rows · ${table.headers.length} columns`}><div className="inline-actions"><button className="btn btn-ghost btn-sm" onClick={() => setRaw(!raw)}><Grid3X3 size={15} /> {raw ? "Grid view" : "Raw view"}</button><CopyButton value={csv} label="Copy table" /><DownloadButton filename="invoice-line-items.csv" content={csv} type="text/csv" label="CSV" /></div></TabHeader>{raw ? <pre className="raw-code">{JSON.stringify(table, null, 2)}</pre> : <div className="extracted-table"><table><thead><tr>{table.headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{table.rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>}<div className="table-quality"><span>Table confidence</span><Confidence value={table.confidence} /></div></div>; }
function QueriesTab({ onTrace }: { onTrace: (box: BoundingBox, label: string) => void }) { return <div className="tab-stack"><TabHeader icon={<FileSearchIcon />} title="Query answers" count={`${invoiceResult.queries.length} targeted questions`} /><div className="query-results">{invoiceResult.queries.map((query) => <button key={query.id} onClick={() => onTrace(query.boundingBox, query.alias)}><span className="query-number">Q</span><div><small>QUESTION</small><h3>{query.question}</h3><small>ANSWER</small><strong>{query.answer}</strong><div><Confidence value={query.confidence} /><em>Page {query.boundingBox.page}</em><span><Focus size={14} /> Source Trace</span></div></div></button>)}</div></div>; }
function FileSearchIcon() { return <Search size={18} />; }
function SignaturesTab({ onTrace }: { onTrace: (box: BoundingBox, label: string) => void }) { return <div className="tab-stack"><TabHeader icon={<Signature size={18} />} title="Detected signatures" count="Presence and location only" /><div className="signature-disclaimer"><InfoIcon /><p><strong>Signature detection is not biometric verification.</strong> Amazon Textract can identify a signature’s presence and approximate location, not validate the signer’s identity.</p></div>{invoiceResult.signatures.map((signature) => <button className="signature-result" key={signature.id} onClick={() => onTrace(signature.boundingBox, "Signature")}><span><Signature size={23} /></span><div><strong>Signature detected</strong><p>Page {signature.page} · Bounding area {signature.boundingBox.width}% × {signature.boundingBox.height}%</p></div><Confidence value={signature.confidence} /><StatusBadge status={signature.status} /><Focus size={16} /></button>)}</div>; }
function InfoIcon() { return <AlertTriangle size={18} />; }
function LayoutTab() { return <div className="tab-stack"><TabHeader icon={<LayoutDashboard size={18} />} title="Document layout" count="Reading structure and element hierarchy" /><div className="layout-tree"><div><span>PAGE 1</span><strong>Title</strong><em>INVOICE</em></div><div><span>LAYOUT_HEADER</span><strong>Vendor identity</strong><em>Acme Systems</em></div><div><span>LAYOUT_SECTION_HEADER</span><strong>Bill To</strong><em>Meridian Retail Pvt. Ltd.</em></div><div><span>TABLE</span><strong>Invoice line items</strong><em>3 rows · 4 columns</em></div><div><span>LAYOUT_FOOTER</span><strong>Payment terms</strong><em>Payment due within 15 days</em></div></div></div>; }
function RawJsonTab() { const normalized = { documentId: invoiceResult.documentId, documentType: invoiceResult.documentType, pages: invoiceResult.pages, confidence: invoiceResult.overallConfidence, fields: invoiceResult.fields.map(({ id, label, value, confidence, boundingBox }) => ({ id, label, value, confidence, geometry: { boundingBox } })), tables: invoiceResult.tables, queries: invoiceResult.queries, signatures: invoiceResult.signatures }; const json = JSON.stringify(normalized, null, 2); return <div className="tab-stack"><TabHeader icon={<FileJson size={18} />} title="Normalized JSON" count={`${(json.length / 1024).toFixed(1)} KB demo response`}><div className="inline-actions"><CopyButton value={json} /><DownloadButton filename="demo-001-normalized.json" content={json} type="application/json" label="JSON" /></div></TabHeader><pre className="raw-code syntax-json">{json}</pre><p className="raw-note">A compact normalized example is shown. This is not a full AWS Textract Block response.</p></div>; }
