"use client";

import Link from "next/link";
import { useRef, useState } from "react";
import { AlertTriangle, ArrowLeft, Braces, Check, CheckCircle2, ClipboardCheck, Download, Expand, Eye, EyeOff, FileJson, FileText, Focus, Grid3X3, LayoutDashboard, Minus, MoreHorizontal, Plus, RotateCw, ScanLine, Search, Signature, Table2, Text } from "lucide-react";
import { Card, Confidence, CopyButton, DownloadButton, EmptyState, StatusBadge } from "@/components/ui/common";
import { PipelineIndicator } from "@/components/ui/pipeline-indicator";
import { useDocuments } from "@/hooks/use-documents";
import { useExtractionResult } from "@/hooks/use-extraction-result";
import { useApp } from "@/lib/context/app-context";
import type { BoundingBox, ExtractionResult, ProcessingStage } from "@/lib/types";
import { cn, downloadFile, maskValue } from "@/lib/utils/format";
import { formatDocumentDate, getDocumentStatusLabel } from "@/lib/utils/documents";

const tabs = ["Overview", "Text", "Fields", "Tables", "Queries", "Signatures", "Layout", "Raw JSON"] as const;
type Tab = typeof tabs[number];

export function DocumentWorkspace({ id }: { id: string }) {
  const { getDocument, isLoading: documentsLoading } = useDocuments(); const document = getDocument(id); const extraction = useExtractionResult(id, !documentsLoading && Boolean(document) && document?.status === "COMPLETED");
  const { settings, updateSettings, toast } = useApp(); const [tab, setTab] = useState<Tab>("Overview"); const [selected, setSelected] = useState<BoundingBox | null>(null); const [selectedLabel, setSelectedLabel] = useState(""); const [heatmap, setHeatmap] = useState(false); const [zoom, setZoom] = useState(88); const [rotation, setRotation] = useState(0); const [page, setPage] = useState(1); const viewerRef = useRef<HTMLDivElement>(null);
  if (documentsLoading || (document?.status === "COMPLETED" && extraction.isLoading)) return <WorkspaceLoading />;
  if (!document) return <EmptyState icon={<FileText size={30} />} title="Document not found" description={`No demo document matches “${id}”. It may have been removed from local demo data.`} action={<Link className="btn btn-primary" href="/documents">Back to Documents</Link>} />;
  if (document.status === "FAILED") return <EmptyState icon={<AlertTriangle size={30} />} title="Processing failed" description="The mock pipeline stopped safely and no processing animation is still running." action={<Link className="btn btn-primary" href="/upload">Retry from Upload</Link>} />;
  if (!extraction.data) return <EmptyState icon={<AlertTriangle size={30} />} title="Extraction unavailable" description={extraction.error?.message ?? "No structured extraction is available for this document yet."} action={<button className="btn btn-primary" onClick={extraction.retry}>Retry loading</button>} />;
  const result = extraction.data;
  const trace = (box: BoundingBox, label: string) => { setSelected(box); setSelectedLabel(label); setPage(box.page); toast("Source Trace activated", `${label} highlighted on page ${box.page}.`); };
  const exportAll = (format: "json" | "csv" | "txt") => {
    const content = format === "json" ? JSON.stringify(result, null, 2) : format === "csv" ? `Field,Value,Confidence\n${result.fields.map((field) => `"${field.key}","${field.value}",${field.confidence ?? ""}`).join("\n")}` : result.fullText;
    downloadFile(`${document.id}-extraction.${format}`, content, format === "json" ? "application/json" : format === "csv" ? "text/csv" : "text/plain"); toast("Export created", `${format.toUpperCase()} downloaded locally.`);
  };
  return <div className="document-workspace reveal">
    <header className="workspace-header"><div><Link href="/documents" className="back-link"><ArrowLeft size={16} /> Documents</Link><div className="workspace-title"><span><FileText size={20} /></span><div><h1>{document.fileName}</h1><p>{document.id} · {document.pageCount} pages · Processed {formatDocumentDate(document.updatedAt).toLowerCase()}</p></div><StatusBadge status={getDocumentStatusLabel(document)} /></div></div><div className="workspace-actions"><button className={cn("btn btn-secondary", settings.privacyMode && "active")} aria-pressed={settings.privacyMode} onClick={() => updateSettings({ privacyMode: !settings.privacyMode })}>{settings.privacyMode ? <EyeOff size={16} /> : <Eye size={16} />} Privacy {settings.privacyMode ? "On" : "Off"}</button><div className="export-menu"><button className="btn btn-primary" onClick={() => exportAll(settings.exportFormat)}><Download size={16} /> Export {settings.exportFormat.toUpperCase()}</button><button className="btn btn-primary export-more" onClick={() => exportAll("csv")} aria-label="Quick export CSV"><MoreHorizontal size={16} /></button></div></div></header>
    <PipelineIndicator activeIndex={getPipelineIndex(document.processingStage)} complete={document.status === "COMPLETED"} compact />
    <div className="workspace-body">
      <section className="viewer-panel" ref={viewerRef}><div className="viewer-toolbar"><div className="tool-group"><button className="icon-btn" onClick={() => setZoom(Math.max(50, zoom - 10))} aria-label="Zoom out"><Minus size={17} /></button><span>{zoom}%</span><button className="icon-btn" onClick={() => setZoom(Math.min(150, zoom + 10))} aria-label="Zoom in"><Plus size={17} /></button><button className="toolbar-btn" onClick={() => setZoom(88)}><Focus size={16} /> Fit</button></div><div className="tool-group"><button className="toolbar-btn" onClick={() => setPage(Math.max(1, page - 1))} disabled={page === 1}>‹</button><span>Page <strong>{page}</strong> of {document.pageCount}</span><button className="toolbar-btn" onClick={() => setPage(Math.min(document.pageCount, page + 1))} disabled={page === document.pageCount}>›</button></div><div className="tool-group"><button className="icon-btn" onClick={() => setRotation((rotation + 90) % 360)} aria-label="Rotate page"><RotateCw size={17} /></button><button className="icon-btn" onClick={() => void viewerRef.current?.requestFullscreen?.()} aria-label="Fullscreen viewer"><Expand size={17} /></button></div></div>
        <div className="viewer-canvas"><div className="viewer-hud-label" aria-hidden="true"><span>SOURCE_DOCUMENT</span><em>PAGE_{String(page).padStart(2,"0")}</em></div><div className="viewer-hud-corners" aria-hidden="true"><i /><i /><i /><i /></div><div className="paper-wrap" style={{ width: `${zoom}%` }}><MockInvoicePage page={page} rotation={rotation} /><div className="page-overlays">{selected?.page === page && <span className="source-highlight" style={{ left: `${selected.left}%`, top: `${selected.top}%`, width: `${selected.width}%`, height: `${selected.height}%` }}><em>{selectedLabel}</em></span>}{heatmap && result.fields.filter((field) => field.boundingBox?.page === page).map((field, index) => { const box = field.boundingBox; if (!box) return null; const confidence = field.confidence ?? 0; return <span title={`${field.key}: ${confidence}%`} className={cn("heat-region", confidence >= 90 ? "high" : confidence >= 80 ? "medium" : "low")} key={field.id} style={{ left: `${box.left}%`, top: `${box.top}%`, width: `${box.width}%`, height: `${box.height}%`, animationDelay: `${Math.min(index, 8) * 35}ms` }} />; })}</div></div></div>
        <div className="viewer-footer"><button className={cn("heatmap-toggle", heatmap && "active")} aria-pressed={heatmap} onClick={() => setHeatmap(!heatmap)}><span><Grid3X3 size={15} /> Confidence Heatmap</span><i /></button>{heatmap && <div className="heat-legend"><span><i className="high" /> High 90–100</span><span><i className="medium" /> Medium 80–89.99</span><span><i className="low" /> Low below 80</span></div>}<div className="source-trace-info"><ScanLine size={15} /><span><strong>Source Trace</strong><small>Trace extracted data back to its exact source location.</small></span></div></div>
      </section>
      <section className="results-panel"><div className="result-tabs" role="tablist" aria-label="Extraction result views">{tabs.map((item) => <button type="button" role="tab" id={`result-tab-${item.toLowerCase().replaceAll(" ", "-")}`} aria-controls="result-tabpanel" aria-selected={tab === item} tabIndex={tab === item ? 0 : -1} className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</div><div className="result-content" id="result-tabpanel" role="tabpanel" aria-labelledby={`result-tab-${tab.toLowerCase().replaceAll(" ", "-")}`} key={tab}>
        {tab === "Overview" && <OverviewTab result={result} />}{tab === "Text" && <TextTab result={result} />}{tab === "Fields" && <FieldsTab result={result} privacy={settings.privacyMode} onTrace={trace} />}{tab === "Tables" && <TablesTab result={result} />}{tab === "Queries" && <QueriesTab result={result} onTrace={trace} />}{tab === "Signatures" && <SignaturesTab result={result} onTrace={trace} />}{tab === "Layout" && <LayoutTab />}{tab === "Raw JSON" && <RawJsonTab result={result} />}
      </div></section>
    </div>
  </div>;
}

function MockInvoicePage({ page, rotation }: { page: number; rotation: number }) {
  if (page > 1) return <div className="invoice-page page-two" style={{ transform: `rotate(${rotation}deg)` }}><div className="invoice-brand"><span>ACME</span><small>SYSTEMS</small></div><h2>Payment terms & authorization</h2><p>Payment is due within 15 days from the date of invoice. Please reference the invoice number in all correspondence.</p><div className="terms-lines">{Array.from({ length: 8 }, (_, index) => <i key={index} />)}</div><div className="signature-area"><span>Authorized signature</span><b>Arun Mehta</b><i /></div><footer>ACME Systems · Bengaluru, Karnataka · accounts@acmesystems.example</footer></div>;
  return <div className="invoice-page" style={{ transform: `rotate(${rotation}deg)` }}><div className="invoice-top"><div className="invoice-brand"><span>ACME</span><small>SYSTEMS</small></div><h2>INVOICE</h2></div><div className="invoice-details"><div><small>FROM</small><strong>Acme Systems</strong><p>14 Cloud Avenue<br/>Bengaluru, Karnataka 560001<br/>accounts@acmesystems.example</p></div><div><dl><dt>Invoice Number</dt><dd>INV-2026-1042</dd><dt>Invoice Date</dt><dd>02 Sep 2026</dd><dt>PO Number</dt><dd>PO-7482O</dd></dl></div></div><div className="bill-to"><small>BILL TO</small><strong>Meridian Retail Pvt. Ltd.</strong><p>98 Residency Road, Bengaluru</p></div><table><thead><tr><th>DESCRIPTION</th><th>QTY</th><th>RATE</th><th>AMOUNT</th></tr></thead><tbody><tr><td>Cloud Infrastructure Setup</td><td>1</td><td>₹32,000.00</td><td>₹32,000.00</td></tr><tr><td>Technical Support</td><td>4</td><td>₹2,000.00</td><td>₹8,000.00</td></tr></tbody></table><div className="invoice-totals"><dl><dt>Subtotal</dt><dd>₹40,000.00</dd><dt>GST (6.45%)</dt><dd>₹2,580.00</dd><dt className="total">TOTAL AMOUNT</dt><dd className="total">₹42,580.00</dd></dl></div><div className="tax-line"><small>TAX ID</small><strong>29ABCDE1234F1Z5</strong></div><p className="thank-you">Thank you for your business.</p><footer>Payment due within 15 days · Page 1 of 2</footer></div>;
}

function getPipelineIndex(stage?: ProcessingStage) {
  if (stage === "SCANNING" || stage === "ANALYZING") return 1;
  if (stage === "EXTRACTING") return 2;
  if (stage === "VERIFYING") return 3;
  return 4;
}

function WorkspaceLoading() {
  return <div className="page-skeleton" aria-label="Loading document workspace"><div className="skeleton skeleton-title" /><div className="workspace-loading-grid"><div className="skeleton skeleton-panel" /><div className="skeleton skeleton-panel" /></div></div>;
}

function TabHeader({ icon, title, count, children }: { icon: React.ReactNode; title: string; count?: string; children?: React.ReactNode }) { return <div className="tab-heading"><div><span>{icon}</span><div><h2>{title}</h2>{count && <p>{count}</p>}</div></div>{children}</div>; }
function OverviewTab({ result: r }: { result: ExtractionResult }) {
  const groups = [
    { label: "High confidence", fields: r.fields.filter((field) => (field.confidence ?? 0) >= 90), level: "high" },
    { label: "Medium confidence", fields: r.fields.filter((field) => (field.confidence ?? 0) >= 80 && (field.confidence ?? 0) < 90), level: "medium" },
    { label: "Needs review", fields: r.fields.filter((field) => (field.confidence ?? 0) < 80), level: "low" },
  ];
  const reviewCount = r.fields.filter((field) => field.reviewStatus === "Pending" || (field.confidence ?? 0) < 85).length;
  return <div className="tab-stack"><TabHeader icon={<LayoutDashboard size={18} />} title="Extraction overview" count="Normalized demo result" /><div className="overview-hero"><div><span>Overall confidence</span><strong>{r.overallConfidence}%</strong><Confidence value={r.overallConfidence} label={false} /></div><span className="quality-badge"><CheckCircle2 size={16} /> High quality</span></div><div className="overview-metrics">{[["Document type",r.documentType],["Pages",r.pages],["Processing time",r.processingTime],["Fields detected",r.fields.length],["Tables detected",r.tables.length],["Signatures",r.signatures.length]].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><Card className="confidence-distribution"><div className="card-heading"><div><h3>Confidence distribution</h3><p>Across extracted fields</p></div></div><div className="distribution-bars">{groups.map(({ label, fields, level }) => { const value = r.fields.length ? Math.round(fields.length / r.fields.length * 100) : 0; return <div key={label}><span>{label}</span><div><i className={level} style={{ width: `${value}%` }} /></div><strong>{value}%</strong><small>{fields.length} {fields.length === 1 ? "field" : "fields"}</small></div>; })}</div></Card>{reviewCount > 0 ? <div className="review-callout"><span><ClipboardCheck size={19} /></span><div><strong>{reviewCount} {reviewCount === 1 ? "field needs" : "fields need"} human review</strong><p>Low-confidence values are already in the Confidence-Guided Review queue.</p></div><Link href="/review">Review fields</Link></div> : <div className="review-callout review-clear"><span><CheckCircle2 size={19} /></span><div><strong>No fields require review</strong><p>All extracted fields meet the current confidence policy.</p></div></div>}</div>;
}
function TextTab({ result }: { result: ExtractionResult }) { const [search, setSearch] = useState(""); const text = result.fullText; return <div className="tab-stack"><TabHeader icon={<Text size={18} />} title="Detected text" count={`${text.length} characters`}><CopyButton value={text} /></TabHeader><label className="inline-search"><Search size={15} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search extracted text" /></label><pre className="extracted-text">{search ? text.split(new RegExp(`(${search.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")})`, "ig")).map((part, index) => part.toLowerCase() === search.toLowerCase() ? <mark key={index}>{part}</mark> : part) : text}</pre><div className="info-callout"><ScanLine size={16} /> Text is normalized demo content. A backend can later preserve block-level confidence and geometry.</div></div>; }
function FieldsTab({ result, privacy, onTrace }: { result: ExtractionResult; privacy: boolean; onTrace: (box: BoundingBox, label: string) => void }) { return <div className="tab-stack"><TabHeader icon={<Braces size={18} />} title="Extracted fields" count={`${result.fields.length} key-value pairs`} /><div className="field-list">{result.fields.map((field) => <button className="field-row" key={field.id} onClick={() => field.boundingBox && onTrace(field.boundingBox, field.key)}><span className="field-status-icon">{(field.confidence ?? 0) < 80 ? <AlertTriangle /> : <Check />}</span><span className="field-main"><small>{field.key}</small><strong>{privacy && field.sensitive ? maskValue(field.value) : field.value}</strong></span><Confidence value={field.confidence ?? 0} /><StatusBadge status={field.reviewStatus ?? "Pending"} /><span className="trace-action"><Focus size={15} /> Trace</span></button>)}</div><div className="threshold-note"><AlertTriangle size={15} /> Current review threshold: <strong>85%</strong>. Values below it are routed to review.</div></div>; }
function TablesTab({ result }: { result: ExtractionResult }) { const [raw, setRaw] = useState(false); const table = result.tables[0]; if (!table) return <EmptyState icon={<Table2 size={28} />} title="No tables detected" description="This extraction result does not contain a table." />; const csv = `${table.headers.join(",")}\n${table.rows.map((row) => row.map((cell) => `"${cell}"`).join(",")).join("\n")}`; return <div className="tab-stack"><TabHeader icon={<Table2 size={18} />} title="Extracted tables" count={`${table.rows.length} rows · ${table.headers.length} columns`}><div className="inline-actions"><button className="btn btn-ghost btn-sm" onClick={() => setRaw(!raw)}><Grid3X3 size={15} /> {raw ? "Grid view" : "Raw view"}</button><CopyButton value={csv} label="Copy table" /><DownloadButton filename="invoice-line-items.csv" content={csv} type="text/csv" label="CSV" /></div></TabHeader>{raw ? <pre className="raw-code">{JSON.stringify(table, null, 2)}</pre> : <div className="extracted-table"><table><thead><tr>{table.headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{table.rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>}<div className="table-quality"><span>Table confidence</span><Confidence value={table.confidence ?? 0} /></div></div>; }
function QueriesTab({ result, onTrace }: { result: ExtractionResult; onTrace: (box: BoundingBox, label: string) => void }) { return <div className="tab-stack"><TabHeader icon={<FileSearchIcon />} title="Query answers" count={`${result.queries.length} targeted questions`} /><div className="query-results">{result.queries.map((query) => <button key={query.id} onClick={() => onTrace(query.boundingBox, query.alias)}><span className="query-number">Q</span><div><small>QUESTION</small><h3>{query.question}</h3><small>ANSWER</small><strong>{query.answer}</strong><div><Confidence value={query.confidence} /><em>Page {query.boundingBox.page}</em><span><Focus size={14} /> Source Trace</span></div></div></button>)}</div></div>; }
function FileSearchIcon() { return <Search size={18} />; }
function SignaturesTab({ result, onTrace }: { result: ExtractionResult; onTrace: (box: BoundingBox, label: string) => void }) { return <div className="tab-stack"><TabHeader icon={<Signature size={18} />} title="Detected signatures" count="Presence and location only" /><div className="signature-disclaimer"><InfoIcon /><p><strong>Signature detection is not biometric verification.</strong> Amazon Textract can identify a signature’s presence and approximate location, not validate the signer’s identity.</p></div>{result.signatures.map((signature) => <button className="signature-result" key={signature.id} onClick={() => onTrace(signature.boundingBox, "Signature")}><span><Signature size={23} /></span><div><strong>Signature detected</strong><p>Page {signature.page} · Bounding area {signature.boundingBox.width}% × {signature.boundingBox.height}%</p></div><Confidence value={signature.confidence} /><StatusBadge status={signature.status} /><Focus size={16} /></button>)}</div>; }
function InfoIcon() { return <AlertTriangle size={18} />; }
function LayoutTab() { return <div className="tab-stack"><TabHeader icon={<LayoutDashboard size={18} />} title="Document layout" count="Reading structure and element hierarchy" /><div className="layout-tree"><div><span>PAGE 1</span><strong>Title</strong><em>INVOICE</em></div><div><span>LAYOUT_HEADER</span><strong>Vendor identity</strong><em>Acme Systems</em></div><div><span>LAYOUT_SECTION_HEADER</span><strong>Bill To</strong><em>Meridian Retail Pvt. Ltd.</em></div><div><span>TABLE</span><strong>Invoice line items</strong><em>3 rows · 4 columns</em></div><div><span>LAYOUT_FOOTER</span><strong>Payment terms</strong><em>Payment due within 15 days</em></div></div></div>; }
function RawJsonTab({ result }: { result: ExtractionResult }) { const normalized = { documentId: result.documentId, documentType: result.documentType, pages: result.pages, confidence: result.overallConfidence, fields: result.fields.map(({ id, key, value, confidence, boundingBox }) => ({ id, key, value, confidence, geometry: { boundingBox } })), tables: result.tables, queries: result.queries, signatures: result.signatures }; const json = JSON.stringify(normalized, null, 2); return <div className="tab-stack"><TabHeader icon={<FileJson size={18} />} title="Normalized JSON" count={`${(json.length / 1024).toFixed(1)} KB demo response`}><div className="inline-actions"><CopyButton value={json} /><DownloadButton filename={`${result.documentId}-normalized.json`} content={json} type="application/json" label="JSON" /></div></TabHeader><pre className="raw-code syntax-json">{json}</pre><p className="raw-note">A compact normalized example is shown. This is not a full AWS Textract Block response.</p></div>; }
