"use client";

import Link from "next/link";
import { Download, Eye, FileSearch, FileText, Filter, Plus, SearchX, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { Confidence, EmptyState, SearchBox, StatusBadge } from "@/components/ui/common";
import { Modal } from "@/components/ui/modal";
import { useApp } from "@/lib/context/app-context";
import type { DocumentRecord } from "@/lib/types";
import { downloadFile } from "@/lib/utils/format";

export function DocumentRepository() {
  const { documents, removeDocument, toast } = useApp(); const [query, setQuery] = useState(""); const [status, setStatus] = useState("All statuses"); const [type, setType] = useState("All types"); const [sort, setSort] = useState("Newest"); const [deleteTarget, setDeleteTarget] = useState<DocumentRecord | null>(null);
  const filtered = useMemo(() => documents.filter((document) => (document.name.toLowerCase().includes(query.toLowerCase()) || document.id.toLowerCase().includes(query.toLowerCase()) || document.tags.some((tag) => tag.includes(query.toLowerCase()))) && (status === "All statuses" || document.status === status) && (type === "All types" || document.type === type)).sort((a,b) => sort === "Highest Confidence" ? b.confidence-a.confidence : sort === "Lowest Confidence" ? a.confidence-b.confidence : sort === "Oldest" ? a.id.localeCompare(b.id) : b.id.localeCompare(a.id)), [documents, query, status, type, sort]);
  const exportDocument = (document: DocumentRecord) => { downloadFile(`${document.id}.json`, JSON.stringify(document, null, 2), "application/json"); toast("Export created", `${document.name} metadata downloaded.`); };
  return <><div className="repository-toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search filename, tag, or document ID" /><div className="filter-group"><span><Filter size={15} /> Filters</span><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter status"><option>All statuses</option><option>Completed</option><option>Needs Review</option><option>Failed</option></select><select value={type} onChange={(event) => setType(event.target.value)} aria-label="Filter document type"><option>All types</option><option>Invoice</option><option>Application</option><option>Contract</option><option>Business Document</option></select><select value={sort} onChange={(event) => setSort(event.target.value)} aria-label="Sort documents"><option>Newest</option><option>Oldest</option><option>Highest Confidence</option><option>Lowest Confidence</option></select></div></div>
    {filtered.length ? <div className="repository-table table-wrap"><table><thead><tr><th>Document</th><th>Type</th><th>Pages</th><th>Status</th><th>Confidence</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody>{filtered.map((document) => <tr key={document.id}><td><Link className="doc-cell" href={`/documents/${document.id}`}><span className="document-thumb"><FileText size={21} /><small>{document.name.split(".").pop()}</small></span><span><strong>{document.name}</strong><small>{document.id} · {document.size}</small><em>{document.tags.map((tag) => <i key={tag}>{tag}</i>)}</em></span></Link></td><td>{document.type}</td><td>{document.pages}</td><td><StatusBadge status={document.status} /></td><td><Confidence value={document.confidence} /></td><td className="muted-cell">{document.uploadedAt}</td><td><div className="row-actions"><Link className="icon-btn" title="View" href={`/documents/${document.id}`}><Eye size={16} /></Link><Link className="icon-btn" title="Review" href="/review"><FileSearch size={16} /></Link><button className="icon-btn" title="Export" onClick={() => exportDocument(document)}><Download size={16} /></button><button className="icon-btn danger" title="Delete" onClick={() => setDeleteTarget(document)}><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div> : <EmptyState icon={<SearchX size={28} />} title={documents.length ? "No matching documents" : "No documents yet"} description={documents.length ? "Try clearing a filter or searching another term." : "Process your first document to begin building the repository."} action={<Link href="/upload" className="btn btn-primary"><Plus size={16} /> Process Document</Link>} />}
    <div className="repository-footer"><span>Showing {filtered.length} of {documents.length} documents</span><p>Demo records and locally processed metadata are stored in this browser.</p></div>
    <Modal open={Boolean(deleteTarget)} onClose={() => setDeleteTarget(null)} title="Remove document?" actions={<><button className="btn btn-secondary" onClick={() => setDeleteTarget(null)}>Cancel</button><button className="btn btn-danger" onClick={() => { if (deleteTarget) { removeDocument(deleteTarget.id); toast("Document removed", `${deleteTarget.name} was removed from local demo data.`); setDeleteTarget(null); } }}><Trash2 size={16} /> Remove document</button></>}><div className="confirm-copy"><span><Trash2 size={22} /></span><p><strong>{deleteTarget?.name}</strong> will be removed from this browser’s demo history. This cannot be undone unless local demo data is reset.</p></div></Modal>
  </>;
}
