"use client";

import Link from "next/link";
import { AlertTriangle, Check, CheckCircle2, Clock3, Edit3, Eye, Flag, History, Save, SkipForward, UserCheck, X } from "lucide-react";
import { useMemo, useState } from "react";
import { Confidence, EmptyState, Segmented, StatusBadge } from "@/components/ui/common";
import { useApp } from "@/lib/context/app-context";
import type { ReviewItem } from "@/lib/types";

type Filter = "All" | "Low Confidence" | "Edited" | "Flagged" | "Approved";

export function ReviewQueue() {
  const { reviews, updateReview, toast } = useApp(); const [filter, setFilter] = useState<Filter>("All"); const [threshold, setThreshold] = useState(85); const [selected, setSelected] = useState(reviews[0]?.id ?? "");
  const filtered = useMemo(() => reviews.filter((item) => item.confidence <= threshold && (filter === "All" || (filter === "Low Confidence" ? item.confidence < 80 : item.status === filter))), [reviews, filter, threshold]);
  const current = filtered.find((item) => item.id === selected) ?? filtered[0];
  const act = (item: ReviewItem, status: "Approved" | "Flagged" | "Skipped", label: string) => { updateReview(item.id, status); toast(label, `${item.field} in ${item.documentName}.`); };
  return <div className="review-layout">
    <section className="review-list-panel"><div className="review-toolbar"><Segmented value={filter} options={["All","Low Confidence","Edited","Flagged","Approved"]} onChange={setFilter} ariaLabel="Review filters" /><label className="threshold-filter"><span>Threshold</span><input type="range" min="50" max="99" value={threshold} onChange={(event) => setThreshold(Number(event.target.value))} /><strong>{threshold}%</strong></label></div><div className="review-summary"><span><strong>{filtered.length}</strong> items in view</span><span><AlertTriangle size={14} /> {reviews.filter((item) => item.status === "Pending").length} awaiting action</span></div>
      {filtered.length ? <div className="review-items">{filtered.map((item) => <button className={selected === item.id || current?.id === item.id ? "active" : ""} onClick={() => setSelected(item.id)} key={item.id}><span className={item.confidence < 80 ? "review-severity low" : "review-severity medium"}><AlertTriangle size={16} /></span><div><div><strong>{item.field}</strong><StatusBadge status={item.status} /></div><p>{item.machineValue}</p><small>{item.documentName} · Page {item.page}</small></div><Confidence value={item.confidence} /></button>)}</div> : <EmptyState icon={<CheckCircle2 size={29} />} title="Queue is clear" description="No review items match this filter and threshold." />}
    </section>
    <section className="review-detail">{current ? <ReviewDetail key={current.id} item={current} onAction={act} /> : <EmptyState icon={<UserCheck size={30} />} title="Select a review item" description="Choose a field from the queue to validate it." />}</section>
  </div>;
}

function ReviewDetail({ item, onAction }: { item: ReviewItem; onAction: (item: ReviewItem, status: "Approved" | "Flagged" | "Skipped", label: string) => void }) {
  const { updateReview, toast } = useApp(); const [editing, setEditing] = useState(false); const [value, setValue] = useState(item.reviewedValue ?? item.machineValue);
  const save = () => { if (!value.trim()) return; updateReview(item.id, "Edited", value.trim()); setEditing(false); toast("Field corrected", `${item.field} updated to ${value.trim()}.`); };
  return <><div className="review-detail-head"><div><span className="eyebrow">FIELD REVIEW</span><h2>{item.field}</h2><p>{item.documentName} · Page {item.page}</p></div><Link className="btn btn-secondary btn-sm" href={`/documents/${item.documentId}`}><Eye size={15} /> Open document</Link></div><div className="reason-banner"><AlertTriangle size={17} /><div><strong>{item.reason}</strong><p>Machine confidence is {item.confidence.toFixed(1)}%, below the configured review policy.</p></div></div><div className="compare-grid"><div><span>MACHINE EXTRACTED VALUE</span><strong>{item.machineValue}</strong><small><Clock3 size={13} /> Original · immutable</small></div><div className="reviewed-value"><span>REVIEWED VALUE</span>{editing ? <input autoFocus value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") save(); }} /> : <strong>{item.reviewedValue ?? "Not reviewed yet"}</strong>}<small><UserCheck size={13} /> {item.updatedAt ?? "Awaiting reviewer"}</small></div></div><div className="review-confidence"><div><span>Extraction confidence</span><Confidence value={item.confidence} /></div><StatusBadge status={item.status} /></div><div className="review-actions">{editing ? <><button className="btn btn-primary" onClick={save}><Save size={16} /> Save correction</button><button className="btn btn-secondary" onClick={() => { setEditing(false); setValue(item.reviewedValue ?? item.machineValue); }}><X size={16} /> Cancel</button></> : <><button className="btn btn-primary" onClick={() => onAction(item, "Approved", "Field approved")}><Check size={16} /> Approve</button><button className="btn btn-secondary" onClick={() => setEditing(true)}><Edit3 size={16} /> Edit value</button><button className="btn btn-secondary" onClick={() => onAction(item, "Flagged", "Field flagged")}><Flag size={16} /> Flag</button><button className="btn btn-ghost" onClick={() => onAction(item, "Skipped", "Field skipped")}><SkipForward size={16} /> Skip</button></>}</div><div className="audit-section"><div className="card-heading"><div><h3><History size={17} /> Machine vs Human Audit Trail</h3><p>Local demo history designed for future DynamoDB persistence.</p></div></div><div className="audit-timeline">{item.audit.map((event) => <div key={event.id}><span>{event.timestamp}</span><i className={event.actor.toLowerCase()}>{event.actor === "Reviewer" ? <UserCheck size={14} /> : event.actor === "Textract" ? <Eye size={14} /> : <AlertTriangle size={14} />}</i><div><strong>{event.action}</strong><p>{event.detail}</p><small>{event.actor}</small></div></div>)}</div></div></>;
}
