"use client";

import Link from "next/link";
import { ArrowRight, Check, CheckCircle2, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { AuthShell } from "@/components/auth/auth-shell";
import { MascotVisual } from "@/components/auth/mascot-visual";

export function LoginExperience() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [visible, setVisible] = useState(false); const [focused, setFocused] = useState(false); const [complete, setComplete] = useState(false);
  const submit = (event: FormEvent) => { event.preventDefault(); if (email && password) setComplete(true); };
  return <AuthShell visual={<MascotVisual compact privacyLookAway={visible} attentionTarget={!visible && focused ? "password" : null} />}><div className="auth-form-wrap auth-login-wrap reveal">{complete ? <div className="auth-success"><span><CheckCircle2 size={30} /></span><p className="eyebrow">DEMO SIGN-IN COMPLETE</p><h1>Welcome to the workspace.</h1><p>No remote session was created and your password was not stored. Continue into the frontend demo.</p><Link className="btn btn-primary btn-lg full-width" href="/dashboard">Open Workspace <ArrowRight size={17} /></Link><small><ShieldCheck size={14} /> Frontend-only authentication state</small></div> : <><div className="auth-title"><p className="eyebrow">WELCOME BACK</p><h1>Sign in to your workspace</h1><p>Access the Textract Studio frontend demonstration.</p></div><form className="auth-form" onSubmit={submit}><label><span>Email Address</span><div className="auth-input"><Mail size={16} /><input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@university.edu" required /></div></label><label><span>Password</span><div className="auth-input" data-mascot-target="password"><LockKeyhole size={16} /><input type={visible ? "text" : "password"} autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} onFocus={() => setFocused(true)} onBlur={() => setFocused(false)} placeholder="Enter your password" required /><button type="button" onClick={() => setVisible(!visible)} aria-label={visible ? "Hide password" : "Show password"}>{visible ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label><div className="login-options"><label className="auth-check"><input type="checkbox" /><i><Check size={10} /></i><span>Remember me on this device</span></label><Link href="/forgot-password">Forgot password?</Link></div><button type="submit" className="btn btn-primary btn-lg full-width">Sign In <ArrowRight size={17} /></button></form><p className="auth-switch">Don&apos;t have an account? <Link href="/signup">Create Account</Link></p><div className="auth-honesty"><LockKeyhole size={14} /><span><strong>Demo authentication</strong>Credentials are validated only for form completeness and never persisted.</span></div></>}</div></AuthShell>;
}

