"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck, UserRound } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { MascotVisual } from "@/components/auth/mascot-visual";
import { AuthShell } from "@/components/auth/auth-shell";

export function SignupExperience() {
  const [step, setStep] = useState<1 | 2>(1); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [visible, setVisible] = useState(false); const [focus, setFocus] = useState<"password" | "confirm" | null>(null); const [complete, setComplete] = useState(false); const [touched, setTouched] = useState(false);
  const requirements = useMemo(() => [{ label: "8+ characters", met: password.length >= 8 },{ label: "Upper & lowercase", met: /[a-z]/.test(password) && /[A-Z]/.test(password) },{ label: "One number", met: /\d/.test(password) },{ label: "Special character", met: /[^A-Za-z0-9]/.test(password) }], [password]);
  const score = requirements.filter((item) => item.met).length; const strength = ["Weak", "Weak", "Fair", "Good", "Strong"][score]; const basicValid = name.trim().length > 1 && /^\S+@\S+\.\S+$/.test(email); const securityValid = score === 4 && password === confirm;
  const submit = (event: FormEvent) => { event.preventDefault(); setTouched(true); if (securityValid) setComplete(true); };
  return <AuthShell visual={<MascotVisual privacyLookAway={visible} attentionTarget={visible ? null : focus} />}>
    <div className="auth-form-wrap reveal">{complete ? <div className="auth-success"><span><CheckCircle2 size={30} /></span><p className="eyebrow">DEMO FLOW COMPLETE</p><h1>Your workspace is ready to explore.</h1><p>This frontend demonstration did not create or store an account. A future Cognito-backed service can replace this step.</p><div><Link className="btn btn-primary btn-lg" href="/dashboard">Launch Workspace <ArrowRight size={17} /></Link><Link className="btn btn-secondary btn-lg" href="/login">Return to Sign In</Link></div><small><ShieldCheck size={14} /> No password or account data was persisted.</small></div> : <>
      <div className="auth-progress"><span className={step >= 1 ? "active" : ""}><i>{step > 1 ? <Check size={12} /> : "1"}</i> Basic information</span><em /><span className={step === 2 ? "active" : ""}><i>2</i> Account security</span></div>
      <div className="auth-title"><p className="eyebrow">WELCOME TO TEXTRACT STUDIO</p><h1>{step === 1 ? "Create your account" : "Secure your account"}</h1><p>{step === 1 ? "Start with a few details. This is a frontend-only account experience." : "Choose a strong password. Nothing you type is stored or sent."}</p></div>
      {step === 1 ? <form onSubmit={(event) => { event.preventDefault(); setTouched(true); if (basicValid) { setTouched(false); setStep(2); } }} className="auth-form"><label><span>Full Name</span><div className="auth-input"><UserRound size={16} /><input autoComplete="name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Enter your full name" required /></div>{touched && name.trim().length <= 1 && <small className="field-error">Enter your full name.</small>}</label><label><span>Email Address</span><div className="auth-input"><Mail size={16} /><input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@university.edu" required /></div>{touched && !/^\S+@\S+\.\S+$/.test(email) && <small className="field-error">Enter a valid email address.</small>}</label><button className="btn btn-primary btn-lg full-width" type="submit">Continue <ArrowRight size={17} /></button></form> : <form onSubmit={submit} className="auth-form"><button type="button" className="auth-back-step" onClick={() => { setTouched(false); setStep(1); }}><ArrowLeft size={14} /> Edit basic information</button><PasswordInput label="Password" value={password} onChange={setPassword} visible={visible} onVisibility={() => setVisible(!visible)} target="password" onFocus={() => setFocus("password")} onBlur={() => setFocus(null)} autoComplete="new-password" /><div className="password-strength"><div className="strength-head"><span>Password strength</span><strong className={`strength-${score}`}>{password ? strength : "Not set"}</strong></div><div className="strength-meter">{[1,2,3,4].map((level) => <i className={score >= level ? `filled level-${score}` : ""} key={level} />)}</div><div className="password-rules">{requirements.map((item) => <span className={item.met ? "met" : ""} key={item.label}><i>{item.met && <Check size={9} />}</i>{item.label}</span>)}</div></div><PasswordInput label="Confirm Password" value={confirm} onChange={setConfirm} visible={visible} onVisibility={() => setVisible(!visible)} target="confirm" onFocus={() => setFocus("confirm")} onBlur={() => setFocus(null)} autoComplete="new-password" />{touched && password !== confirm && <small className="field-error standalone">Passwords do not match.</small>}<label className="auth-check"><input type="checkbox" required /><i><Check size={10} /></i><span>I agree to the demo workspace terms and understand no account is stored remotely.</span></label><button className="btn btn-primary btn-lg full-width" type="submit">Create Account <ArrowRight size={17} /></button></form>}
      <p className="auth-switch">Already have an account? <Link href="/login">Sign in</Link></p><div className="auth-honesty"><LockKeyhole size={14} /><span><strong>Demo authentication</strong>No Cognito or remote account service is connected.</span></div>
    </>}</div>
  </AuthShell>;
}

function PasswordInput({ label, value, onChange, visible, onVisibility, target, onFocus, onBlur, autoComplete }: { label: string; value: string; onChange: (value: string) => void; visible: boolean; onVisibility: () => void; target: "password" | "confirm"; onFocus: () => void; onBlur: () => void; autoComplete: string }) {
  return <label><span>{label}</span><div className="auth-input" data-mascot-target={target}><LockKeyhole size={16} /><input type={visible ? "text" : "password"} value={value} onChange={(event) => onChange(event.target.value)} onFocus={onFocus} onBlur={onBlur} autoComplete={autoComplete} placeholder={label === "Password" ? "Create a strong password" : "Re-enter your password"} required /><button type="button" onClick={onVisibility} aria-label={visible ? `Hide ${label.toLowerCase()}` : `Show ${label.toLowerCase()}`} title={visible ? "Hide password" : "Show password"}>{visible ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label>;
}

